{% set name = "freva-rest-server" %}
{% set version = "2411.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/FREVA-CLINT/freva-nextgen/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7227d57d637e67c1204e00e9e2aae6f4169a0df1e004c01f0e58172a354f3e9a

build:
  number: 5
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}
    - aiohttp
    - apache-solr
    - email-validator
    - fastapi
    - fastapi-third-party-auth
    - mongodb
    - motor >=3.6
    - mysql-server
    - pyjwt
    - pymongo >=4.9
    - python-dotenv
    - python-dateutil
    - python-multipart
    - redis-py
    - redis-server
    - requests
    - rich
    - rich-argparse
    - setuptools
    - tomli
    - typing_extensions
    - uvicorn
    - zarr

test:
  imports:
    - freva_rest
  commands:
    - freva-rest-server --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Server for the Free Evaluation and Analysis Framework (Freva)
  home: https://github.com/FREVA-CLINT/freva-nextgen
  description: |
    Freva, the free evaluation system framework, is a data search and analysis
    platform developed by the atmospheric science community for the atmospheric
    science community. With help of Freva researchers can

      * quickly and intuitively search for data stored at typical data centers that
        host many datasets.
      * create a common interface for user defined data analysis tools.
      * apply data analysis tools in a reproducible manner.

      The *freva-rest-server* defines endpoints that make up the freva server
      services.

      The server needs various systemd services to function properly, e.g apache-solr
      mondoDB. Those systemd services are located unter
      `$CONDA_PREFIX/share/systemd/<SERVICE>.service`. If you want to enable one
      or multiple services you can copy the `*.service` files either to
      `/etc/systemd/system` or `~/.local/share/systemd/user/`.


  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
